### ISSUE TITLE
running scripts with dollar quoting fails

### ISSUE THREAD

**Issue by LuboVarga** [soulwing/fluent-jdbc#5]
Running [dollar quoted|https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING] thing will fail.
```
            FluentJdbc fluentJdbc = new FluentJdbc(connPostgres);
            fluentJdbc.executeScript(new StringSQLSource(
                "DO $$\n" +
                    "BEGIN\n" +
                    "  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'somenicelovercaserole') THEN\n" +
                    "    CREATE ROLE somenicelovercaserole;\n" +
                    "  END IF;\n" +
                    "END\n" +
                    "$$;"
            ));
```

exception like:
```
Caused by: org.soulwing.jdbc.SQLRuntimeException: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 3 in SQL DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'somenicelovercaserole') THEN CREATE ROLE somenicelovercaserole. Expected terminating $$
	at org.soulwing.jdbc.FluentJdbc.doExecute(FluentJdbc.java:159)
	at org.soulwing.jdbc.FluentJdbc.executeScript(FluentJdbc.java:123)
	at sk.nike....a(Test.java:47)
	... 26 more
Caused by: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 3 in SQL DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'somenicelovercaserole') THEN CREATE ROLE somenicelovercaserole. Expected terminating $$
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1226)
	at org.postgresql.core.Parser.parseSql(Parser.java:1115)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:1067)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:17)
	at org.postgresql.util.LruCache.borrow(LruCache.java:115)
	at org.postgresql.core.QueryExecutorBase.borrowQuery(QueryExecutorBase.java:271)
	at org.postgresql.jdbc.PgConnection.borrowQuery(PgConnection.java:146)
```

Just for info, this will run fine:
```
            fluentJdbc.executeScript(new StringSQLSource(
                "DO '\n" +
                    "BEGIN\n" +
                    "  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = ''somenicelovercaserole'') THEN\n" +
                    "    CREATE ROLE somenicelovercaserole;\n" +
                    "  END IF;\n" +
                    "END\n" +
                    "';"
            ));
```

PS: off topic, there is a clash with project [fluent-jdbc by zsoltherpai](https://github.com/zsoltherpai/fluent-jdbc)

**Comment by ceharris** [comment]
As noted in the wiki docs, the parser used by `executeScript` isn't smart enough to handle SQL block constructs. You should be able to execute this statement using `execute` instead.

**Comment by LuboVarga** [comment]
Using execute does not work either. And it would not solve my problem either, as I have given statement as part of larger sql script resource file.

PS: I have handled it by changing quoting from double dollar to single apostrophe (and escaping things inside of it).

**Comment by ceharris** [comment]
Version 2.x supports PostgreSQL dollar quoting as described in the [Wiki](https://github.com/soulwing/fluent-jdbc/wiki/Executing-SQL-DDL-and-DML-Statements#support-for-postgresql-dollar-quoted-string-constants).
